services:
  next-app:
    container_name: docs-app
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - docs_network

  postgres:
    container_name: docs-postgres
    image: postgres:16-alpine
    restart: always
    env_file:
      - ../.env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docs_network

networks:
  docs_network:
    driver: bridge

volumes:
  postgres_data:
