
FROM node:23-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./

RUN corepack enable pnpm && pnpm i

COPY src ./src
COPY public ./public
COPY prisma ./prisma
COPY next.config.ts .
COPY tsconfig.json .
COPY tailwind.config.ts .
COPY postcss.config.mjs .
COPY next-env.d.ts .
COPY .eslintrc.json .
COPY components.json .
COPY jest.config.mjs .
COPY commitlint.config.js .

RUN pnpm exec prisma generate

CMD sh -c "if [ -f pnpm-lock.yaml ]; then pnpm dev; else npm run dev; fi"